### ISSUE TITLE
Compilation cannot find -lsds_lib on Pynq 2.4

### ISSUE THREAD

**Issue by riple** [EECS-NTNU/bismo#3]
I am trying Pynq 2.4, and I ran into this:
_/usr/bin/arm-linux-gnueabihf-ld: cannot find -lsds_lib
collect2: error: ld returned 1 exit status_

The command I am running is: ./compile_sw.sh, which invokes
_g++ -std=c++11 *.cpp -lsds_lib -o app_

I am using the rootfs from
https://www.xilinx.com/member/forms/download/xef.html?filename=pynq_rootfs_arm_v2.4.zip

**Comment by maltanar** [comment]
This release was tested with v1.4 only, but you can try replacing the -lsds_lib with -lcma and see if this resolves the issue.

**Comment by riple** [comment]
Hi maltanar,

I changed the script to -lcma, and it complains about:
/usr/lib/gcc/arm-linux-gnueabihf/7/../../../../lib/libcma.so: undefined reference to `pthread_spin_init'
/usr/lib/gcc/arm-linux-gnueabihf/7/../../../../lib/libcma.so: undefined reference to `pthread_spin_unlock'
/usr/lib/gcc/arm-linux-gnueabihf/7/../../../../lib/libcma.so: undefined reference to `pthread_create'
/usr/lib/gcc/arm-linux-gnueabihf/7/../../../../lib/libcma.so: undefined reference to `pthread_key_create'
/usr/lib/gcc/arm-linux-gnueabihf/7/../../../../lib/libcma.so: undefined reference to `pthread_getspecific'
/usr/lib/gcc/arm-linux-gnueabihf/7/../../../../lib/libcma.so: undefined reference to `pthread_spin_lock'
/usr/lib/gcc/arm-linux-gnueabihf/7/../../../../lib/libcma.so: undefined reference to `pthread_spin_destroy'
/usr/lib/gcc/arm-linux-gnueabihf/7/../../../../lib/libcma.so: undefined reference to `pthread_join'
/usr/lib/gcc/arm-linux-gnueabihf/7/../../../../lib/libcma.so: undefined reference to `pthread_setspecific'

is there a header file that I should include?

**Comment by maltanar** [comment]
Sounds like you may need the -pthread option passed to g++ as well.

**Comment by riple** [comment]
Great! It works now. Thank you, maltanar!
